TEMPLATE = app
QT = gui core qt3support
CONFIG += qt release warn_on console
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/rebaseDialog.ui
HEADERS = src/rebaseDialogimpl.h
SOURCES = src/rebaseDialogimpl.cpp src/main.cpp
