#!/bin/sh

# remove trailing whitespaces, tabs and carriage returns.

SED=$(which sed)
MV=$(which mv)

if [ -z "${SED}" ]; then 
      exit 1
fi

if [ -z "${MV}" ]; then 
      exit 1
fi

for i in "$@";
do
	"${SED}" "s/[\r\t ]*$//" "$i" > tmp.bak;
	"${MV}" -f tmp.bak "$i";
done;
